baseURL = "/"
languageCode = "en-us"
title = "rogs"
theme = "archie"
staticDir = ["static"]
copyright = "© Roger Gonzalez"


[permalinks]
  posts = "/:year/:month/:title/"

[params]
  author = "Roger Gonzalez"
  subtitle = "my blog, thoughts and other stuff"
  avatar = "me.png"
  mode = "dark"

  [[params.social]]
    name = "fas fa-envelope"
    url = "mailto:roger@rogs.me"
  [[params.social]]
    name = "fab fa-git"
    url = "https://git.rogs.me/"
  [[params.social]]
    name = "fab fa-gitlab"
    url = "https://gitlab.com/rogs"
  [[params.social]]
    name = "fab fa-linkedin-in"
    url = "https://linkedin.com/in/rogergonzalez21"
  [[params.social]]
    name = "fas fa-rss"
    url = "https://rogs.me/index.xml"

  [[params.projects.personal]]
    name = "montevideo.restaurant"
    url = "https://montevideo.restaurant/"
    description = "A restaurant index page for the city of Montevideo (Uruguay)."
    github = "https://github.com/rogsme/montevideo.restaurant"
    rogsgit = "https://git.rogs.me/montevideo.restaurant.git/"
  [[params.projects.personal]]
    name = "YAMS"
    url = "https://yams.media/"
    description = "A higly opinionated media server"
    gitlab = "https://gitlab.com/rogs/yams"
    rogsgit = "https://git.rogs.me/yams.git/"

  [[params.projects.work]]
    name = "Certn - Workday integration"
    url = "/resume/certn-workday/"
    description = "This is the main Workday integration for Certn."
    client = "lazer"
  [[params.projects.work]]
    name = "Certn - ADA DINER"
    url = "/resume/certn-ada-diner/"
    description = "An app that triggers crawls on demand, to check criminal records for a certain person."
    client = "lazer"
  [[params.projects.work]]
    name = "Certn - International framework"
    url = "/resume/certn-intl-framework/"
    description = "An app that acts like a bridge between their main app (Certn) and criminal background check providers (like the RCMP)."
    client = "lazer"
  [[params.projects.work]]
    name = "Volition"
    url = "/resume/volition/"
    description = "A series of crawlers for different screws and fasteners vendors."
    client = "tarmac"
  [[params.projects.work]]
    name = "CocaCola - Tus Tapas Valen"
    url = "/resume/tus-tapas-valen/"
    description = 'The main "Tus tapas valen" app for CocaCola Mexico.'
    client = "massive"
  [[params.projects.work]]
    name = "Axelerist"
    url = "/resume/axelerist/"
    description = "A web app that connects to an external API and displays the client’s inventory in a more friendly and ergonomic way."
    client = "vascar"
  [[params.projects.work]]
    name = "Knac"
    url = "/resume/knac/"
    description = "A job application startup, empathizing on assessments to recommend candidates to a specific job."
    client = "vascar"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 3

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 4

[[menu.main]]
name = "Donate"
url = "/donate/"
weight = 5

[markup.goldmark.renderer]
  unsafe = true
