baseURL = "https://rogs.me/"
languageCode = "en-us"
title = "rogs"
theme = "archie"
staticDir = ["static"]
copyright = "© Roger Gonzalez"


[permalinks]
  posts = "/:year/:month/:title/"

[params]
  author = "Roger Gonzalez"
  subtitle = "my blog, thoughts and other stuff"
  avatar = "me.png"
  mode = "dark"

  [[params.social]]
    name = "mail"
    url = "mailto:roger@rogs.me"
  [[params.social]]
    name = "gitlab"
    url = "https://gitlab.com/rogs"
  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/rogergonzalez21"
  [[params.social]]
    name = "rss"
    url = "https://rogs.me/index.xml"

  [[params.webring]]
    name = "hotline"
    url = "https://hotlinewebring.club/"
    nextUrl = "https://hotlinewebring.club/rogs/next"
    prevUrl = "https://hotlinewebring.club/rogs/previous"
  [[params.webring]]
    name = "nojs"
    url = "https://nojs.sugarfi.dev/"
    nextUrl = "https://nojs.sugarfi.dev/next.php?url=https://rogs.me/"
    prevUrl = "https://nojs.sugarfi.dev/prev.php?url=https://rogs.me/"
  [[params.webring]]
    name = "retronaut"
    url = "https://webring.dinhe.net/"
    nextUrl = "https://webring.dinhe.net/next/https://rogs.me"
    prevUrl = "https://webring.dinhe.net/prev/https://rogs.me"
  [[params.webring]]
    name = "devring"
    url = "https://devring.club/"
    nextUrl = "https://devring.club/sites/11/next"
    prevUrl = "https://devring.club/sites/11/prev"
  [[params.webring]]
    name = "geekring"
    url = "https://geekring.net/"
    nextUrl = "http://geekring.net/site/242/next"
    prevUrl = "http://geekring.net/site/242/previous"
  [[params.webring]]
    name = "theoldnet"
    url = "https://webring.theoldnet.com/"
    nextUrl = "https://webring.theoldnet.com/member/142f64c0e28d2272ed620c96265b2505/next/navigate"
    prevUrl = "https://webring.theoldnet.com/member/142f64c0e28d2272ed620c96265b2505/previous/navigate"

  [[params.projects.personal]]
    name = "YAMS"
    url = "https://yams.media/"
    description = "A higly opinionated media server"
    gitea = "https://git.rogs.me/rogs/yams"
    gitlab = "https://gitlab.com/rogs/yams"
    github = "https://github.com/rogsme/yams"
  [[params.projects.personal]]
    name = "ForgeLLM"
    url = "https://melpa.org/#/forge-llm"
    description = "forge-llm brings LLM-powered PR descriptions to Emacs—auto-generating clear, structured summaries from your git diffs."
    gitea = "https://git.rogs.me/rogs/forge-llm"
    gitlab = "https://gitlab.com/rogs/forge-llm"
    github = "https://github.com/rogsme/forge-llm"
  [[params.projects.personal]]
    name = "subscleaner"
    url = "https://pypi.org/project/subscleaner/"
    description = "A Python script that removes advertisements from subtitle files."
    gitea = "https://git.rogs.me/rogs/subscleaner"
    gitlab = "https://gitlab.com/rogs/subscleaner"
    github = "https://github.com/rogsme/subscleaner"
  [[params.projects.personal]]
    name = "bitwarden-to-keepass"
    url = "https://gitlab.com/rogs/bitwarden-to-keepass"
    description = "Export (most of) your Bitwarden items into KeePass (kdbx) database. That includes logins - with TOTP seeds, URIs, custom fields, attachments and secure notes"
    gitea = "https://git.rogs.me/rogs/bitwarden-to-keepass"
    gitlab = "https://gitlab.com/rogs/bitwarden-to-keepass"
    github = "https://github.com/rogsme/bitwarden-to-keepass"
  [[params.projects.personal]]
    name = "montevideo.restaurant"
    url = "https://montevideo.restaurant/"
    description = "A restaurant index page for the city of Montevideo (Uruguay)."
    gitea = "https://git.rogs.me/rogs/montevideo.restaurant"
    github = "https://github.com/rogsme/montevideo.restaurant"
    gitlab = "https://gitlab.com/rogs/montevideo.restaurant"
  [[params.projects.personal]]
    name = "caldav2google"
    url = "https://gitlab.com/rogs/caldav2google"
    description = "A Python utility that seamlessly syncs your CalDAV calendar to Google Calendar, with smart change detection and event tracking."
    gitea = "https://git.rogs.me/rogs/caldav2google"
    gitlab = "https://gitlab.com/rogs/caldav2google"
    github = "https://github.com/rogsme/caldav2google"
  [[params.projects.personal]]
    name = "synapse-docker-bridges"
    url = "https://gitlab.com/rogs/dendrite-docker-bridges"
    description = "Self-host your own Matrix server with WhatsApp, Telegram & Discord bridges - all configured automatically via Docker! Simple setup scripts handle the heavy lifting, letting you connect your favorite chat platforms in minutes."
    gitea = "https://git.rogs.me/rogs/synapse-docker-bridges"
    gitlab = "https://gitlab.com/rogs/synapse-docker-bridges"
    github = "https://github.com/rogsme/synapse-docker-bridges"
  [[params.projects.personal]]
    name = "cleanmedia"
    url = "https://gitlab.com/rogs/cleanmedia"
    description = "A poor man's data rentention policy tool for dendrite home servers"
    gitea = "https://git.rogs.me/rogs/cleanmedia"
    gitlab = "https://gitlab.com/rogs/cleanmedia"
    github = "https://github.com/rogsme/cleanmedia"
  [[params.projects.personal]]
    name = "TimelapseTuner"
    url = "https://git.rogs.me/rogs/timeplapse_tuner"
    description = "Timelapse Tuner is a Bash script that automates the process of creating timelapse videos with randomly selected background music. It merges a timelapse video file with a randomly chosen audio file from the current directory, applying fade-in and fade-out effects to the audio for a polished result"
    gitea = "https://git.rogs.me/rogs/timeplapse_tuner"
    gitlab = "https://gitlab.com/rogs/timelapse_tuner"
    github = "https://github.com/rogsme/timelapse_tuner"

  [[params.projects.work]]
    name = "Fable Upskill"
    url = "/resume/fable-upskill/"
    description = "An LMS designed to support accessibility and inclusivity for people with disabilities"
    client = "lazer2"
  [[params.projects.work]]
    name = "Ario"
    url = "/resume/ario/"
    description = "An AI for busy parents"
    client = "lazer2"
  [[params.projects.work]]
    name = "Certn - Workday integration"
    url = "/resume/certn-workday/"
    description = "This is the main Workday integration for Certn."
    client = "lazer"
  [[params.projects.work]]
    name = "Certn - ADA DINER"
    url = "/resume/certn-ada-diner/"
    description = "An app that triggers crawls on demand, to check criminal records for a certain person."
    client = "lazer"
  [[params.projects.work]]
    name = "Certn - International framework"
    url = "/resume/certn-intl-framework/"
    description = "An app that acts like a bridge between their main app (Certn) and criminal background check providers (like the RCMP)."
    client = "lazer"
  [[params.projects.work]]
    name = "Volition"
    url = "/resume/volition/"
    description = "A series of crawlers for different screws and fasteners vendors."
    client = "tarmac"
  [[params.projects.work]]
    name = "CocaCola - Tus Tapas Valen"
    url = "/resume/tus-tapas-valen/"
    description = 'The main "Tus tapas valen" app for CocaCola Mexico.'
    client = "massive"
  [[params.projects.work]]
    name = "Axelerist"
    url = "/resume/axelerist/"
    description = "A web app that connects to an external API and displays the client’s inventory in a more friendly and ergonomic way."
    client = "vascar"
  [[params.projects.work]]
    name = "Knac"
    url = "/resume/knac/"
    description = "A job application startup, empathizing on assessments to recommend candidates to a specific job."
    client = "vascar"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 3

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 4

[[menu.main]]
name = "Donate"
url = "/donate/"
weight = 5

[markup.goldmark.renderer]
  unsafe = true
