baseURL = "https://rogs.me/"
languageCode = "en-us"
title = "rogs"
theme = "archie"
staticDir = ["static"]
paginate=3 # articles per page
copyright = "© Roger Gonzalez"


[permalinks]
  posts = "/:year/:month/:title/"

[params]
  author = "Roger Gonzalez"
  subtitle = "my blog, thoughts and other stuff"
  avatar = "avatar.png"
  mode = "dark"

  [[params.social]]
    name = "fas fa-envelope"
    url = "mailto:roger@rogs.me"
  [[params.social]]
    name = "fab fa-git"
    url = "https://git.rogs.me/"
  [[params.social]]
    name = "fab fa-gitlab"
    url = "https://gitlab.com/rogs"
  [[params.social]]
    name = "fab fa-linkedin-in"
    url = "https://linkedin.com/in/rogergonzalez21"
  [[params.social]]
    name = "fas fa-rss"
    url = "https://rogs.me/index.xml"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Resume"
url = "/resume"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 3

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 4

[[menu.main]]
name = "Contact"
url = "/contact"
weight = 5

[markup.goldmark.renderer]
  unsafe = true
