baseURL = "https://blog.rogs.me"
languageCode = "en-us"
title = "rogs | Blog"
theme = "m10c"
staticDir = ["static"]

[permalinks]
  posts = "/:year/:month/:title/"

[params]
  author = "Roger Gonzalez"
  description = "my blog, thoughts and other stuff"
  avatar = "avatar.png"
  [[params.social]]
    name = "fas fa-globe"
    url = "https://rogs.me"
  [[params.social]]
    name = "fas fa-envelope"
    url = "mailto:roger@rogs.me"
  [[params.social]]
    name = "fab fa-git"
    url = "https://git.rogs.me/me"
  [[params.social]]
    name = "fab fa-linkedin"
    url = "https://linkedin.com/in/rogergonzalez21"
  [[params.social]]
    name = "fab fa-twitter"
    url = "https://twitter.com/rogergonzalez21"
  [[params.social]]
    name = "fab fa-keybase"
    url = "https://keybase.io/rogs"
  [[params.social]]
    name = "fas fa-rss"
    url = "https://blog.rogs.me/index.xml"
  [[params.donations]]
    name = "fab fa-bitcoin"
    url = "btc.txt"
  [[params.donations]]
    name = "fab fa-ethereum"
    url = "eth.txt"
  [[params.donations]]
    name = "fab fa-paypal"
    url = "https://www.paypal.me/rogsme21"

[params.style]
  darkestColor = "#38761d"
  darkColor = "#212121"
  lightColor = "#fafafa"
