baseURL = "https://rogs.me/"
languageCode = "en-us"
title = "rogs"
theme = "archie"
staticDir = ["static"]
copyright = "© Roger Gonzalez"


[permalinks]
  posts = "/:year/:month/:title/"

[params]
  author = "Roger Gonzalez"
  subtitle = "my blog, thoughts and other stuff"
  avatar = "me.png"
  mode = "dark"

  [[params.social]]
    name = "mail"
    url = "mailto:roger@rogs.me"
  [[params.social]]
    name = "git-commit"
    url = "https://git.rogs.me/"
  [[params.social]]
    name = "gitlab"
    url = "https://gitlab.com/rogs"
  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/rogergonzalez21"
  [[params.social]]
    name = "rss"
    url = "https://rogs.me/index.xml"

  [[params.webring]]
    name = "hotline"
    url = "https://hotlinewebring.club/"
    nextUrl = "https://hotlinewebring.club/rogs/next"
    prevUrl = "https://hotlinewebring.club/rogs/previous"
  [[params.webring]]
    name = "nojs"
    url = "https://nojs.sugarfi.dev/"
    nextUrl = "https://nojs.sugarfi.dev/next.php?url=https://rogs.me/"
    prevUrl = "https://nojs.sugarfi.dev/prev.php?url=https://rogs.me/"
  [[params.webring]]
    name = "retronaut"
    url = "https://webring.dinhe.net/"
    nextUrl = "https://webring.dinhe.net/next/https://rogs.me"
    prevUrl = "https://webring.dinhe.net/prev/https://rogs.me"
  [[params.webring]]
    name = "devring"
    url = "https://devring.club/"
    nextUrl = "https://devring.club/sites/11/next"
    prevUrl = "https://devring.club/sites/11/prev"
  [[params.webring]]
    name = "geekring"
    url = "https://geekring.net/"
    nextUrl = "http://geekring.net/site/242/next"
    prevUrl = "http://geekring.net/site/242/previous"
  [[params.webring]]
    name = "theoldnet"
    url = "https://webring.theoldnet.com/"
    nextUrl = "https://webring.theoldnet.com/member/142f64c0e28d2272ed620c96265b2505/next/navigate"
    prevUrl = "https://webring.theoldnet.com/member/142f64c0e28d2272ed620c96265b2505/previous/navigate"

  [[params.projects.personal]]
    name = "montevideo.restaurant"
    url = "https://montevideo.restaurant/"
    description = "A restaurant index page for the city of Montevideo (Uruguay)."
    github = "https://github.com/rogsme/montevideo.restaurant"
    rogsgit = "https://git.rogs.me/montevideo.restaurant.git"
    gitlab = "https://gitlab.com/rogs/montevideo.restaurant"
  [[params.projects.personal]]
    name = "YAMS"
    url = "https://yams.media/"
    description = "A higly opinionated media server"
    gitlab = "https://gitlab.com/rogs/yams"
    rogsgit = "https://git.rogs.me/yams.git/"
  [[params.projects.personal]]
    name = "subscleaner"
    url = "https://pypi.org/project/subscleaner/"
    description = "A Python script that removes advertisements from subtitle files."
    rogsgit = "https://git.rogs.me/subscleaner.git/"
    gitlab = "https://gitlab.com/rogs/subscleaner"
  [[params.projects.personal]]
    name = "ute_homeassistant_integration "
    url = "https://github.com/rogsme/ute_homeassistant_integration"
    description = "Home Assistant UTE (Administración Nacional de Usinas y Trasmisiones Eléctricas) component for Uruguay 🇺🇾"
    github = "https://github.com/rogsme/ute_homeassistant_integration"
    gitlab = "https://gitlab.com/rogs/ute_homeassistant_integration"
  [[params.projects.personal]]
    name = "ute-wrapper"
    url = "https://pypi.org/project/ute-wrapper/"
    description = "A convenient wrapper for interacting with the UTE (Administración Nacional de Usinas y Trasmisiones Eléctricas) API in Uruguay 🇺🇾"
    rogsgit = "https://git.rogs.me/ute.git/"
    gitlab = "https://gitlab.com/rogs/ute"
  [[params.projects.personal]]
    name = "The Infinite Website"
    url = "https://theinfinitewebsite.com/"
    description = "A web application that dynamically generates HTML on runtime using ChatGPT and serves it in an async Flask application."
    gitlab = "https://gitlab.com/rogs/the-infinite-website"
    rogsgit = "https://git.rogs.me/the-infinite-website.git/"

  [[params.projects.work]]
    name = "Fable Upskill"
    url = "/resume/fable-upskill/"
    description = "An LMS designed to support accessibility and inclusivity for people with disabilities"
    client = "lazer2"
  [[params.projects.work]]
    name = "Ario"
    url = "/resume/ario/"
    description = "An AI for busy parents"
    client = "lazer2"
  [[params.projects.work]]
    name = "Certn - Workday integration"
    url = "/resume/certn-workday/"
    description = "This is the main Workday integration for Certn."
    client = "lazer"
  [[params.projects.work]]
    name = "Certn - ADA DINER"
    url = "/resume/certn-ada-diner/"
    description = "An app that triggers crawls on demand, to check criminal records for a certain person."
    client = "lazer"
  [[params.projects.work]]
    name = "Certn - International framework"
    url = "/resume/certn-intl-framework/"
    description = "An app that acts like a bridge between their main app (Certn) and criminal background check providers (like the RCMP)."
    client = "lazer"
  [[params.projects.work]]
    name = "Volition"
    url = "/resume/volition/"
    description = "A series of crawlers for different screws and fasteners vendors."
    client = "tarmac"
  [[params.projects.work]]
    name = "CocaCola - Tus Tapas Valen"
    url = "/resume/tus-tapas-valen/"
    description = 'The main "Tus tapas valen" app for CocaCola Mexico.'
    client = "massive"
  [[params.projects.work]]
    name = "Axelerist"
    url = "/resume/axelerist/"
    description = "A web app that connects to an external API and displays the client’s inventory in a more friendly and ergonomic way."
    client = "vascar"
  [[params.projects.work]]
    name = "Knac"
    url = "/resume/knac/"
    description = "A job application startup, empathizing on assessments to recommend candidates to a specific job."
    client = "vascar"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
name = "Resume"
url = "/resume/"
weight = 3

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 4

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 5

[[menu.main]]
name = "Donate"
url = "/donate/"
weight = 6

[markup.goldmark.renderer]
  unsafe = true
