name: CI

on:
  push:
    branches:
      - master

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Greet
        run: echo "CI is working on Gitea!"
